### ISSUE TITLE
Not enough filters

### ISSUE THREAD

**Issue by MatthewWaller** [mlrobsmt/kDS2iOS#2]
Hello, I'm unable to get the CoreML Model working. 

I get the warning: "AUBIO WARNING: not enough filters, 26 allocated but 40 requested."

The the console says:

 read 28966 frames at 16000 Hz
[[-15.2908821, 1.5631789, 0.306849003, 0.198946118, 0.202008247, 0.296782613, 0.00775456429, 0.115254343, 0.0745122433, 0.0563454628, -0.0391116142, 0.0927294493, 0.00377327204, 0.0387161374, -0.00587368011, 0.0453475118, 0.00572639704, 0.0188564658, 0.00835749507, 0.0255236626, ...

Any idea of what's going on?

**Comment by MatthewWaller** [comment]
Nevermind, I worked out what I needed. Thanks!

**Comment by geetasg** [comment]
hello, can you please share what you had to change? I am facing similar issue. Thanks
